import type { PortfolioData } from "../types/portfolio";

const now = new Date().toISOString();

export const defaultPortfolioData: PortfolioData = {
  personalInfo: {
    fullName: "Rashvath Shetty",
    designation: "Software Developer",
    shortBio:
      "Software Developer focused on secure, scalable frontend systems with React, Next.js, and TypeScript.",
    aboutMe:
      "I am a Software Developer at Ekfrazo Technologies Pvt. Ltd., working across the frontend stack on enterprise client projects. I joined as a Software Developer Intern in February 2025 and was converted to a full-time Software Developer in September 2025 based on performance.\nMy work includes building reusable UI systems, integrating APIs, implementing secure authentication and authorization flows, and improving reliability through robust error handling and testing practices.",
    location: "Bangalore, Karnataka, India",
    email: "rashvathshetty4@gmail.com",
    phone: "+91 9148050368",
    linkedinUrl: "https://linkedin.com/in/rashvath-shetty-507438286",
    githubUrl: "https://github.com/rashvath",
    twitterUrl: "",
    resumeUrl: "https://www.rashvath-shetty.in/",
    profilePicture: "",
  },
  projects: [
    {
      id: "proj-1",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      title: "AU Bank - Multi-Currency Forex Platform",
      description:
        "Engineered buy, reload, and sell forex modules with onboarding, card-holder, and ETB flows in Next.js App Router and TypeScript. Implemented OTP sessions with JWT validation, middleware protection, and resilient auth fallback handling.",
      techStack: ["Next.js", "TypeScript", "Redux Toolkit", "Axios", "JWT"],
      projectImage: "",
      liveUrl: "",
      githubUrl: "",
      startDate: "",
      endDate: "",
      featured: true,
      displayOrder: 1,
    },
    {
      id: "proj-2",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      title: "EbixCash - Card Distribution Platform",
      description:
        "Built a role-based platform for Admin, Relationship Manager, Agent, and Treasurer workflows with multi-level transaction approvals, settlement screens, middleware-driven RBAC, and reusable dashboards/forms/tables.",
      techStack: ["Next.js", "TypeScript", "React Query", "Jest", "npm audit"],
      projectImage: "",
      liveUrl: "",
      githubUrl: "",
      startDate: "",
      endDate: "",
      featured: true,
      displayOrder: 2,
    },
    {
      id: "proj-3",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      title: "Target Peak - Admin Portal",
      description:
        "Developed an EdTech admin console covering authentication, academic setup, course management, reporting, and issue tracking. Implemented permission-based navigation, token refresh with single-flight retries, and reusable RHF+Zod form systems.",
      techStack: ["React", "TypeScript", "Vite", "React Hook Form", "Zod", "Axios", "Razorpay"],
      projectImage: "",
      liveUrl: "",
      githubUrl: "",
      startDate: "",
      endDate: "",
      featured: true,
      displayOrder: 3,
    },
    {
      id: "proj-4",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      title: "Bank of India - Corporate Website",
      description:
        "Built responsive corporate website pages and reusable templates/components in Sitefinity CMS, ensuring cross-browser compatibility and brand consistency across sections.",
      techStack: ["HTML", "CSS", "JavaScript", "Sitefinity CMS"],
      projectImage: "",
      liveUrl: "",
      githubUrl: "",
      startDate: "",
      endDate: "",
      featured: true,
      displayOrder: 4,
    },
    {
      id: "proj-5",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      title: "E-commerce App",
      description:
        "Full-featured online store with product filtering, cart, and checkout functionality.",
      techStack: ["React", "Redux", "Tailwind CSS"],
      projectImage: "",
      liveUrl: "https://ecommerce-theta-tan-34.vercel.app",
      githubUrl: "",
      startDate: "",
      endDate: "",
      featured: true,
      displayOrder: 5,
    },
    {
      id: "proj-6",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      title: "Crypto Tracker",
      description:
        "Real-time cryptocurrency prices and charts with authentication and wishlist features.",
      techStack: ["Next.js", "CoinGecko API", "Chart.js", "Clerk Auth"],
      projectImage: "",
      liveUrl: "https://crypto-git-main-rashvaths-projects.vercel.app",
      githubUrl: "",
      startDate: "",
      endDate: "",
      featured: true,
      displayOrder: 6,
    },
    {
      id: "proj-7",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      title: "WeatherNow",
      description:
        "Live weather updates with animated, location-aware responsive UI.",
      techStack: ["React", "Weather API", "Tailwind CSS"],
      projectImage: "",
      liveUrl: "https://rashvath.github.io/WeatherNow",
      githubUrl: "",
      startDate: "",
      endDate: "",
      featured: true,
      displayOrder: 7,
    },
  ],
  skills: [
    {
      id: "skill-1",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      name: "JavaScript",
      proficiency: 90,
      category: "Languages",
      icon: "Code2",
      displayOrder: 1,
    },
    {
      id: "skill-2",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      name: "TypeScript",
      proficiency: 88,
      category: "Languages",
      icon: "FileCode",
      displayOrder: 2,
    },
    {
      id: "skill-3",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      name: "HTML5",
      proficiency: 90,
      category: "Languages",
      icon: "FileCode",
      displayOrder: 3,
    },
    {
      id: "skill-4",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      name: "CSS3",
      proficiency: 88,
      category: "Languages",
      icon: "FileCode",
      displayOrder: 4,
    },
    {
      id: "skill-5",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      name: "React.js",
      proficiency: 92,
      category: "Frontend",
      icon: "Code2",
      displayOrder: 5,
    },
    {
      id: "skill-6",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      name: "Next.js",
      proficiency: 89,
      category: "Frontend",
      icon: "Layout",
      displayOrder: 6,
    },
    {
      id: "skill-7",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      name: "Tailwind CSS",
      proficiency: 90,
      category: "Frontend",
      icon: "Layout",
      displayOrder: 7,
    },
    {
      id: "skill-8",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      name: "Material UI",
      proficiency: 84,
      category: "Frontend",
      icon: "Layout",
      displayOrder: 8,
    },
    {
      id: "skill-9",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      name: "Node.js",
      proficiency: 80,
      category: "Backend",
      icon: "Code2",
      displayOrder: 9,
    },
    {
      id: "skill-10",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      name: "Express.js",
      proficiency: 78,
      category: "Backend",
      icon: "Code2",
      displayOrder: 10,
    },
    {
      id: "skill-11",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      name: "PostgreSQL",
      proficiency: 78,
      category: "Databases",
      icon: "Database",
      displayOrder: 11,
    },
    {
      id: "skill-12",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      name: "Redux Toolkit",
      proficiency: 87,
      category: "State Management",
      icon: "Layout",
      displayOrder: 12,
    },
    {
      id: "skill-13",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      name: "React Query",
      proficiency: 85,
      category: "State Management",
      icon: "Layout",
      displayOrder: 13,
    },
    {
      id: "skill-14",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      name: "TanStack Query",
      proficiency: 85,
      category: "State Management",
      icon: "Layout",
      displayOrder: 14,
    },
    {
      id: "skill-15",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      name: "React Hook Form",
      proficiency: 87,
      category: "Validation & Forms",
      icon: "Layout",
      displayOrder: 15,
    },
    {
      id: "skill-16",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      name: "Formik",
      proficiency: 80,
      category: "Validation & Forms",
      icon: "Layout",
      displayOrder: 16,
    },
    {
      id: "skill-17",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      name: "Yup",
      proficiency: 78,
      category: "Validation & Forms",
      icon: "Layout",
      displayOrder: 17,
    },
    {
      id: "skill-18",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      name: "Zod",
      proficiency: 86,
      category: "Validation & Forms",
      icon: "Layout",
      displayOrder: 18,
    },
    {
      id: "skill-19",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      name: "Sitefinity CMS",
      proficiency: 76,
      category: "CMS",
      icon: "Wrench",
      displayOrder: 19,
    },
    {
      id: "skill-20",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      name: "Git",
      proficiency: 88,
      category: "Tools",
      icon: "Wrench",
      displayOrder: 20,
    },
    {
      id: "skill-21",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      name: "GitHub",
      proficiency: 88,
      category: "Tools",
      icon: "Wrench",
      displayOrder: 21,
    },
    {
      id: "skill-22",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      name: "VS Code",
      proficiency: 92,
      category: "Tools",
      icon: "Wrench",
      displayOrder: 22,
    },
    {
      id: "skill-23",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      name: "Vercel",
      proficiency: 82,
      category: "Tools",
      icon: "Wrench",
      displayOrder: 23,
    },
    {
      id: "skill-24",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      name: "Clerk",
      proficiency: 78,
      category: "Tools",
      icon: "Wrench",
      displayOrder: 24,
    },
    {
      id: "skill-25",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      name: "Axios",
      proficiency: 88,
      category: "Tools",
      icon: "Wrench",
      displayOrder: 25,
    },
    {
      id: "skill-26",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      name: "REST APIs",
      proficiency: 89,
      category: "Concepts",
      icon: "Code2",
      displayOrder: 26,
    },
    {
      id: "skill-27",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      name: "JWT Authentication",
      proficiency: 87,
      category: "Concepts",
      icon: "Code2",
      displayOrder: 27,
    },
    {
      id: "skill-29",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      name: "Middleware",
      proficiency: 86,
      category: "Concepts",
      icon: "Code2",
      displayOrder: 29,
    },
    {
      id: "skill-30",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      name: "RBAC",
      proficiency: 85,
      category: "Concepts",
      icon: "Code2",
      displayOrder: 30,
    },
    {
      id: "skill-31",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      name: "Secure Sessions",
      proficiency: 85,
      category: "Concepts",
      icon: "Code2",
      displayOrder: 31,
    },
    {
      id: "skill-33",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      name: "Responsive Design",
      proficiency: 90,
      category: "Concepts",
      icon: "Code2",
      displayOrder: 33,
    },
    {
      id: "skill-34",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      name: "Agile",
      proficiency: 85,
      category: "Concepts",
      icon: "Code2",
      displayOrder: 34,
    },
    {
      id: "skill-35",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      name: "Scrum",
      proficiency: 84,
      category: "Concepts",
      icon: "Code2",
      displayOrder: 35,
    },
  ],
  experience: [
    {
      id: "exp-1",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      companyName: "Ekfrazo Technologies Pvt. Ltd.",
      role: "Software Developer",
      duration: "Feb 2025 - Present",
      location: "Remote",
      description:
        "Joined as a Software Developer Intern and promoted to a full-time Software Developer based on consistent performance and project delivery.\n- Build scalable web applications using React, Next.js, and TypeScript.\n- Develop reusable UI components and design systems.\n- Integrate REST APIs and manage application state.\n- Implement secure authentication and authorization flows.\n- Optimize performance, accessibility, and responsive layouts.\n- Collaborate with backend developers, designers, and QA teams.\n- Maintain code quality through reviews, testing, and best practices.\n- Participate in Agile sprints, planning, and feature delivery.",
      technologiesUsed: [
        "React",
        "Next.js",
        "TypeScript",
        "Vite",
        "Redux Toolkit",
        "React Query",
        "TanStack Query",
        "React Hook Form",
        "Formik",
        "Yup",
        "Zod",
        "Axios",
        "JWT",
        "Node.js",
        "Express.js",
        "PostgreSQL",
        "Sitefinity CMS",
        "Jest",
        "Razorpay",
      ],
    },
  ],
  certifications: [
    {
      id: "cert-1",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      certificateName: "Introduction to Frontend Development",
      issuingOrganization: "SimpliLearn",
      issueDate: "May 2025",
      credentialUrl: "",
      certificateImage: "",
    },
    {
      id: "cert-2",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      certificateName: "React JS Bootcamp",
      issuingOrganization: "LetsUpgrade",
      issueDate: "Apr 2025",
      credentialUrl: "",
      certificateImage: "",
    },
    {
      id: "cert-3",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      certificateName: "React JS for Beginners",
      issuingOrganization: "SimpliLearn",
      issueDate: "May 2025",
      credentialUrl: "",
      certificateImage: "",
    },
  ],
  education: [
    {
      id: "edu-1",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      institutionName: "Dr. BB Hegde First Grade College, Kundapura",
      degree: "Bachelor of Computer Applications (BCA)",
      specialization: "Mangalore University",
      duration: "2021 - 2024",
      grade: "CGPA: 6.25",
    },
    {
      id: "edu-2",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      institutionName: "Seshadripuram PU College, Yelahanka, Bangalore",
      degree: "Pre-University (PU)",
      specialization: "",
      duration: "2019 - 2021",
      grade: "Percentage: 69%",
    },
  ],
  testimonials: [
    {
      id: "t-1",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      name: "Engineering Lead",
      designation: "Technical Lead",
      company: "Ekfrazo Technologies",
      feedback:
        "Rashvath delivers reliable frontend solutions with strong ownership of authentication, architecture, and product quality.",
      profileImage: "",
    },
  ],
  contactInfo: {
    email: "rashvathshetty4@gmail.com",
    phone: "+91 9148050368",
    linkedIn: "https://linkedin.com/in/rashvath-shetty-507438286",
    github: "https://github.com/rashvath",
    twitterX: "",
    portfolioUrl: "https://www.rashvath-shetty.in/",
  },
  settings: {
    darkModeDefault: true,
    portfolioTheme: "modern-dark",
    primaryColor: "#3b82f6",
    secondaryColor: "#22d3ee",
    seoTitle: "Rashvath Shetty | Software Developer",
    seoDescription:
      "Portfolio of Rashvath Shetty, Software Developer specializing in React, Next.js, TypeScript, and secure web application architecture.",
    openGraphImage: "",
  },
  analytics: {
    portfolioVisits: 0,
    resumeDownloads: 0,
    contactFormSubmissions: 0,
    projectViews: {},
  },
  contactSubmissions: [],
  lastUpdated: now,
};
