import type { PortfolioData } from "../types/portfolio";

const now = new Date().toISOString();

export const defaultPortfolioData: PortfolioData = {
  personalInfo: {
    fullName: "Rashvath Shetty",
    designation: "Software Developer",
    shortBio:
      "Building scalable frontend solutions with React, Next.js, and TypeScript.",
    aboutMe:
      "I am a Software Developer at Ekfrazo Technologies, where I build scalable frontend applications using React.js and Next.js with reusable components and modular architecture.\nI started as a Software Developer Intern in February 2025 and was converted to a full-time role in September 2025 based on consistent performance and technical contributions.\nMy work spans frontend systems, REST API integrations, Node.js and Express.js backend development, PostgreSQL workflows, and enterprise CMS customization.",
    location: "Bangalore, Karnataka, India",
    email: "rashvathshetty4@gmail.com",
    phone: "+91 9148050368",
    linkedinUrl: "https://linkedin.com/in/rashvath-shetty-507438286",
    githubUrl: "https://github.com/rashvath",
    twitterUrl: "",
    resumeUrl: "#",
    profilePicture: "",
  },
  projects: [
    {
      id: "proj-1",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      title: "E-commerce App",
      description:
        "Full-featured online store with product filtering, cart management, and checkout functionality.",
      techStack: ["React", "Redux", "Tailwind CSS"],
      projectImage: "",
      liveUrl: "https://ecommerce-theta-tan-34.vercel.app",
      githubUrl: "",
      startDate: "",
      endDate: "",
      featured: true,
      displayOrder: 1,
    },
    {
      id: "proj-2",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      title: "Crypto Tracker",
      description:
        "Real-time cryptocurrency price tracker with charts, auth, and personalized watchlists.",
      techStack: ["Next.js", "Chart.js", "Clerk", "CoinGecko API"],
      projectImage: "",
      liveUrl: "https://crypto-git-main-rashvaths-projects.vercel.app",
      githubUrl: "",
      startDate: "",
      endDate: "",
      featured: true,
      displayOrder: 2,
    },
    {
      id: "proj-3",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      title: "WeatherNow",
      description:
        "Live weather updates with animated, location-aware responsive UI.",
      techStack: ["React", "Weather API", "Tailwind CSS"],
      projectImage: "",
      liveUrl: "https://rashvath.github.io/WeatherNow",
      githubUrl: "",
      startDate: "",
      endDate: "",
      featured: true,
      displayOrder: 3,
    },
  ],
  skills: [
    {
      id: "skill-1",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      name: "JavaScript",
      proficiency: 88,
      category: "Languages",
      icon: "Code2",
      displayOrder: 1,
    },
    {
      id: "skill-2",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      name: "TypeScript",
      proficiency: 85,
      category: "Languages",
      icon: "FileCode",
      displayOrder: 2,
    },
    {
      id: "skill-3",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      name: "HTML",
      proficiency: 90,
      category: "Languages",
      icon: "FileCode",
      displayOrder: 3,
    },
    {
      id: "skill-4",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      name: "CSS",
      proficiency: 87,
      category: "Languages",
      icon: "FileCode",
      displayOrder: 4,
    },
    {
      id: "skill-5",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      name: "React",
      proficiency: 90,
      category: "Frameworks / Libraries",
      icon: "Code2",
      displayOrder: 5,
    },
    {
      id: "skill-6",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      name: "Next.js",
      proficiency: 84,
      category: "Frameworks / Libraries",
      icon: "Layout",
      displayOrder: 6,
    },
    {
      id: "skill-7",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      name: "Tailwind CSS",
      proficiency: 89,
      category: "Frameworks / Libraries",
      icon: "Layout",
      displayOrder: 7,
    },
    {
      id: "skill-8",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      name: "Redux",
      proficiency: 80,
      category: "Frameworks / Libraries",
      icon: "Layout",
      displayOrder: 8,
    },
    {
      id: "skill-9",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      name: "Chart.js",
      proficiency: 76,
      category: "Frameworks / Libraries",
      icon: "Layout",
      displayOrder: 9,
    },
    {
      id: "skill-10",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      name: "Zod",
      proficiency: 78,
      category: "Frameworks / Libraries",
      icon: "Layout",
      displayOrder: 10,
    },
    {
      id: "skill-11",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      name: "Git",
      proficiency: 86,
      category: "Tools & Platforms",
      icon: "Wrench",
      displayOrder: 11,
    },
    {
      id: "skill-12",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      name: "GitHub",
      proficiency: 86,
      category: "Tools & Platforms",
      icon: "Wrench",
      displayOrder: 12,
    },
    {
      id: "skill-13",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      name: "VS Code",
      proficiency: 90,
      category: "Tools & Platforms",
      icon: "Wrench",
      displayOrder: 13,
    },
    {
      id: "skill-14",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      name: "Vercel",
      proficiency: 75,
      category: "Tools & Platforms",
      icon: "Wrench",
      displayOrder: 14,
    },
    {
      id: "skill-15",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      name: "Clerk",
      proficiency: 72,
      category: "Tools & Platforms",
      icon: "Wrench",
      displayOrder: 15,
    },
    {
      id: "skill-16",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      name: "Sitefinity",
      proficiency: 70,
      category: "Tools & Platforms",
      icon: "Wrench",
      displayOrder: 16,
    },
    {
      id: "skill-17",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      name: "Responsive Design",
      proficiency: 89,
      category: "Other Skills",
      icon: "Code2",
      displayOrder: 17,
    },
    {
      id: "skill-18",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      name: "Component Reusability",
      proficiency: 88,
      category: "Other Skills",
      icon: "Code2",
      displayOrder: 18,
    },
    {
      id: "skill-19",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      name: "Form Validation",
      proficiency: 84,
      category: "Other Skills",
      icon: "Code2",
      displayOrder: 19,
    },
    {
      id: "skill-20",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      name: "Debugging",
      proficiency: 85,
      category: "Other Skills",
      icon: "Code2",
      displayOrder: 20,
    },
    {
      id: "skill-21",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      name: "Agile & Scrum",
      proficiency: 80,
      category: "Other Skills",
      icon: "Code2",
      displayOrder: 21,
    },
  ],
  experience: [
    {
      id: "exp-1",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      companyName: "Ekfrazo Technologies Pvt. Ltd.",
      role: "Software Developer",
      duration: "Feb 2025 - Present",
      location: "Remote",
      description:
        "Recruited as a Software Developer Intern (Feb 2025 - Sep 2025) and converted to a full-time Software Developer role based on performance and contributions.\nDeveloped scalable frontend applications using React.js and Next.js with reusable components and modular architecture.\nDesigned and implemented dynamic role-based UI components, forms, and tables to support maintainable and reusable application workflows.\nBuilt responsive interfaces using Tailwind CSS and implemented Zod-based validation for type-safe and secure form handling.\nDesigned and integrated REST APIs for real-time data handling and seamless frontend-backend communication.\nWorked on Node.js and Express.js backend development, building secure APIs with authentication, middleware handling, and role-based access control.\nDesigned and integrated PostgreSQL database workflows including relational data handling, query optimization, and scalable API structures.\nConfigured and customized Sitefinity CMS for enterprise clients, including custom content types and taxonomy structures.\nUsed Git with feature branching, pull requests, and code reviews while collaborating in Agile development environments.",
      technologiesUsed: [
        "React",
        "Next.js",
        "Tailwind CSS",
        "TypeScript",
        "Zod",
        "Node.js",
        "Express.js",
        "PostgreSQL",
      ],
    },
  ],
  certifications: [
    {
      id: "cert-1",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      certificateName: "Introduction to Frontend Development",
      issuingOrganization: "SimpliLearn",
      issueDate: "2025-05-01",
      credentialUrl: "",
      certificateImage: "",
    },
    {
      id: "cert-2",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      certificateName: "React JS Bootcamp",
      issuingOrganization: "LetsUpgrade",
      issueDate: "2025-04-01",
      credentialUrl: "",
      certificateImage: "",
    },
    {
      id: "cert-3",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      certificateName: "React JS for Beginners",
      issuingOrganization: "SimpliLearn",
      issueDate: "2025-05-01",
      credentialUrl: "",
      certificateImage: "",
    },
  ],
  education: [
    {
      id: "edu-1",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      institutionName: "Dr. BB Hegde First Grade College, Kundapura",
      degree: "Bachelor of Computer Applications (BCA)",
      specialization: "Mangalore University",
      duration: "2021 - 2024",
      grade: "CGPA: 6.25",
    },
    {
      id: "edu-2",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      institutionName: "Seshadripuram PU College, Yelahanka, Bangalore",
      degree: "Pre-University (PU)",
      specialization: "",
      duration: "2019 - 2021",
      grade: "Percentage: 69%",
    },
  ],
  testimonials: [
    {
      id: "t-1",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      name: "Team Lead",
      designation: "Engineering Lead",
      company: "Ekfrazo Technologies",
      feedback:
        "Rashvath consistently delivers clean, well-structured code and adapts quickly to changing requirements.",
      profileImage: "",
    },
  ],
  contactInfo: {
    email: "rashvathshetty4@gmail.com",
    phone: "+91 9148050368",
    linkedIn: "https://linkedin.com/in/rashvath-shetty-507438286",
    github: "https://github.com/rashvath",
    twitterX: "",
    portfolioUrl: "https://www.rashvath-shetty.in",
  },
  settings: {
    darkModeDefault: true,
    portfolioTheme: "modern-dark",
    primaryColor: "#3b82f6",
    secondaryColor: "#22d3ee",
    seoTitle: "Rashvath Shetty | Software Developer",
    seoDescription:
      "Portfolio of Rashvath Shetty - React, Next.js, and TypeScript developer.",
    openGraphImage: "",
  },
  analytics: {
    portfolioVisits: 0,
    resumeDownloads: 0,
    contactFormSubmissions: 0,
    projectViews: {},
  },
  contactSubmissions: [],
  lastUpdated: now,
};
