import type { PortfolioData } from "../types/portfolio";

const now = new Date().toISOString();

export const defaultPortfolioData: PortfolioData = {
  personalInfo: {
    fullName: "Rashvath Shetty",
    designation: "Software Developer",
    shortBio:
      "Software Developer focused on secure, scalable frontend systems with React, Next.js, and TypeScript.",
    aboutMe:
      "I am a Software Developer at Ekfrazo Technologies Pvt. Ltd., working across the frontend stack on enterprise client projects. I joined as a Software Developer Intern in February 2025 and was converted to a full-time Software Developer in September 2025 based on performance.\nMy work includes building reusable UI systems, integrating APIs, implementing secure authentication and authorization flows, and improving reliability through robust error handling and testing practices.",
    location: "Bangalore, Karnataka, India",
    email: "rashvathshetty4@gmail.com",
    phone: "+91 9148050368",
    linkedinUrl: "https://linkedin.com/in/rashvath-shetty-507438286",
    githubUrl: "https://github.com/rashvath",
    twitterUrl: "",
    resumeUrl: "https://www.rashvath-shetty.in/",
    profilePicture: "",
  },
  projects: [
    {
      id: "proj-1",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      title: "AU Bank - Multi-Currency Forex Platform",
      description:
        "Engineered buy, reload, and sell forex modules with onboarding, card-holder, and ETB flows in Next.js App Router and TypeScript. Implemented OTP sessions with JWT validation, middleware protection, and resilient auth fallback handling.",
      slug: "au-forex-frontend",
      detailedDescription:
        "AU Forex Frontend\n\nForex Card and Multi-Currency Transaction Platform\n\nOverview\nContributed to a production-grade Next.js and TypeScript fintech application for multi-currency forex card transactions, customer onboarding, document management, authentication, and transaction processing. Worked across secure session handling, API integrations, complex forms, currency workflows, validation, reusable UI components, and transaction-related business logic.\n\nCore Modules\n- Forex Transactions - Buy Currency, Sell Currency, Reload Currency, multi-currency transaction workflows and transaction details.\n- Customer Onboarding - Customer information, travel details, purpose of travel, FATCA and supporting document workflows.\n- Document Management - Upload, preview, delete, compression, file validation, and document-type handling.\n- Authentication and Sessions - OTP-protected workflows, session validation, logout handling, multi-tab session handling, and protected routes.\n- Forex Rates - Currency exchange rates, discounted rates, charges breakdown, and transaction amount calculations.\n- Transaction Management - Transaction fetching, status handling, refund processing, receipt generation, and PDF downloads.\n- Customer Profile - Profile retrieval, session-based data handling, and API request optimization.\n\nPromocode Dashboard (Standalone Module)\n- Built a dedicated Promocode Management Dashboard for applying and managing promotional offers for customers.\n- Implemented promocode validation logic including eligibility checks, expiry validation, and usage constraints.\n- Integrated dynamic discount application based on transaction type, currency, and customer category.\n- Developed reusable Promocode selection and application UI components used across transaction flows.\n- Handled API integration for fetching active, expired, and customer-specific promocodes.\n- Implemented real-time discount recalculation when promocodes are applied or removed.\n- Ensured secure and rule-based promocode application aligned with backend business logic.\n- Designed the module to be reusable across multiple customer-facing transaction screens.\n\nTechnical Contributions\n- Implemented multi-currency Buy, Sell, and Reload transaction flows.\n- Integrated and handled REST APIs using Axios, including custom interceptors and centralized request handling.\n- Implemented OTP-based session validation and protected transaction workflows.\n- Improved session management with revalidation, logout handling, multi-tab conflict detection, and error handling.\n- Built and enhanced Zod-based form validation for customer and transaction workflows.\n- Implemented business-rule validation for customer details, travel information, transaction amounts, and currency operations.\n- Developed document upload workflows with file type and size validation and image compression.\n- Implemented FATCA and supporting-document handling with upload, preview, and deletion functionality.\n- Added transaction receipt and confirmation PDF generation and download functionality.\n- Implemented discounted exchange-rate and charges-breakup calculations.\n- Built reusable dialogs and UI components for promocodes, branch visits, charges, refunds, and transaction workflows.\n- Optimized API usage to prevent duplicate customer/profile requests.\n- Improved UI state handling for loading, validation, errors, empty states, and asynchronous API operations.\n- Worked with strict TypeScript typing across components, forms, API responses, and business logic.\n\nArchitecture\nApplication\n- Next.js App Router\n- React 19\n- TypeScript\n- Server/Client Components\n- Reusable React components\n\nAPI and Data\n- Axios\n- REST API integration\n- Custom Axios interceptors\n- Session/context-based state handling\n- Custom React hooks\n\nValidation and Security\n- Zod\n- OTP authentication\n- Protected routes\n- Session revalidation\n- File validation\n\nUI\n- Material UI (MUI)\n- Tailwind CSS\n- Emotion\n- Responsive form and transaction interfaces\n\nTesting and Quality\n- ESLint\n- TypeScript strict mode\n- Production build validation\n- Git-based development workflow\n\nKey Technical Areas\nNext.js | React | TypeScript | MUI | Tailwind CSS | Axios | Zod | REST APIs | OTP Authentication | Session Management | Form Validation | File Uploads | PDF Generation | Multi-Currency Transactions | Promocode Engine | Fintech\n\nRole\nSoftware Developer - Frontend Development\n\nContributed to feature development, API integration, security/session workflows, business logic, form validation, reusable components, bug fixes, and production-ready frontend implementation across the forex transaction platform.",
      techStack: ["Next.js", "TypeScript", "Redux Toolkit", "Axios", "JWT"],
      projectImage: "",
      liveUrl: "",
      githubUrl: "",
      startDate: "",
      endDate: "",
      featured: true,
      displayOrder: 1,
    },
    {
      id: "proj-2",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      title: "EbixCash - Card Distribution Platform",
      description:
        "Built a role-based platform for Admin, Relationship Manager, Agent, and Treasurer workflows with multi-level transaction approvals, settlement screens, middleware-driven RBAC, and reusable dashboards/forms/tables.",
      slug: "ebixcash-card-distribution-platform",
      detailedDescription:
        "EbixCash - Card Distribution Platform\n\nEnterprise Card Distribution and Treasury Management Platform\n\nOverview\nContributed to a production-grade Next.js and TypeScript enterprise platform supporting Admin, Relationship Manager, Agent, Treasurer, and Checker workflows. Worked across transaction processing, treasury operations, vendor onboarding, reporting, role-based access control, form workflows, and reusable UI architecture.\n\nCore Modules\n- User and Role Management - Role-based user creation, permissions, location mapping, and workflow access.\n- Treasury Operations - Deal mapping, deal ID handling, balance retrieval, settlement, and transaction workflows.\n- Transaction Management - Card transactions, currency operations, approvals, and business-rule validation.\n- Vendor Onboarding - Request creation, update workflows, shared components, and request-summary APIs.\n- Reporting - Transaction reports, settled positions, financial tables, and treasury reporting.\n- Approval Workflows - Multi-level transaction approval and checker workflows.\n- Feedback and Rejection - Rejection summaries, feedback allocation, and workflow state handling.\n\nTechnical Contributions\n- Implemented and refined API data mapping and response handling for treasury workflows.\n- Improved deal ID extraction, balance mapping, and selected-deal state management.\n- Added and corrected reporting table columns and backend field mappings.\n- Implemented role-based dynamic form options for Cluster Head and Relationship Manager workflows.\n- Improved form validation and date-handling logic, including DOB constraints and DatePicker behavior.\n- Added read-only and disabled states for product configuration options.\n- Refactored vendor-onboarding flows into reusable shared components and API utilities.\n- Improved TypeScript typing, null handling, conditional rendering, and edge-case handling.\n- Fixed UI/data inconsistencies across treasury, reporting, settlement, and transaction modules.\n\nArchitecture and Development\nFrontend\n- Next.js\n- React\n- TypeScript\n- React Query\n- Reusable component architecture\n\nApplication Logic\n- REST API integration\n- Role-Based Access Control (RBAC)\n- Form validation\n- Business-rule implementation\n- Dynamic form configuration\n- State management\n\nQuality and Tooling\n- Jest\n- npm Audit\n- Git\n- Code refactoring\n- Type-safe development\n\nKey Areas Worked On\nTreasury | Deal Mapping | Settlement | Transaction Processing | Vendor Onboarding | Reporting | RBAC | Forms | Data Tables | API Integration | Reusable Components\n\nRole\nSoftware Developer - Frontend / Application Development\n\nContributed to feature development, business-logic implementation, bug fixing, UI improvements, API integration, and frontend architecture across multiple enterprise workflows.",
      techStack: ["Next.js", "TypeScript", "React Query", "Jest", "npm audit"],
      projectImage: "",
      liveUrl: "",
      githubUrl: "",
      startDate: "",
      endDate: "",
      featured: true,
      displayOrder: 2,
    },
    {
      id: "proj-3",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      title: "Target Peak - Admin Portal",
      description:
        "Developed an EdTech admin console covering authentication, academic setup, course management, reporting, and issue tracking. Implemented permission-based navigation, token refresh with single-flight retries, and reusable RHF+Zod form systems.",
      slug: "target-peak-web",
      detailedDescription:
        "Target Peak Web\n\nAdmin Management and Analytics Platform\n\nOverview\nContributed to a production-grade React and TypeScript admin platform for managing users, results, payments, support operations, master data, promotions, and system configurations. Worked across reusable component architecture, data-driven dashboards, authentication, API integration, form validation, routing, and multi-environment application setup.\n\nCore Modules\n- Admin Dashboard - Centralized navigation, dashboard views, analytics, and administrative workflows.\n- User Management - User administration, admin management, user settings, student registration tracking, and access control.\n- Results and Performance - Result management, OMR-based evaluation, performance tracking, and data visualization.\n- Financial Management - Paid students, failed payments, OMR students, and payment status tracking.\n- Master Data Management - Roles, streams, subjects, qualifications, events, verticals, and organizational hierarchy.\n- Support Management - WhatsApp, Email, Mobile, and AI support workflows with support categories and ticket management.\n- Promotions and Engagement - Coupon management, promotions, FAQs, live activities, events, and engagement configuration.\n- System Configuration - Role settings, system settings, access control, and application-level configuration.\n\nTechnical Contributions\n- Developed and integrated 25+ administrative pages across user management, results, support, financial, master-data, and configuration modules.\n- Built reusable DynamicTable components for data-driven administrative interfaces.\n- Implemented reusable DynamicForm architecture with configurable fields and validation schemas.\n- Integrated React Hook Form + Zod for type-safe and schema-based form validation.\n- Implemented React Query for API data fetching, caching, synchronization, and server-state management.\n- Integrated backend services using Axios with centralized API configuration.\n- Implemented authentication and route protection using an AuthGate architecture.\n- Developed role-based Access Control workflows for administrative modules.\n- Built reusable UI components using Radix UI and shadcn/ui patterns.\n- Implemented responsive interfaces using Tailwind CSS.\n- Integrated Recharts for dashboard analytics and data visualization.\n- Implemented client-side routing and nested administrative navigation using React Router v6.\n- Configured separate development, staging, and production environments with environment-specific API URLs and application configurations.\n- Configured dedicated runtime ports for development, staging, and production environments.\n- Improved application structure using reusable hooks, shared types, utilities, and component-level abstractions.\n- Worked with a highly type-safe TypeScript architecture across pages, components, API models, forms, and application state.\n\nArchitecture\nApplication\n- React 18\n- TypeScript\n- Vite\n- React Router v6\n- SPA architecture\n- Component-driven architecture\n\nUI\n- Radix UI\n- shadcn/ui patterns\n- Tailwind CSS\n- Reusable dialogs, forms, tables, and UI primitives\n\nAPI and Data\n- Axios\n- TanStack React Query\n- REST API integration\n- Custom React hooks\n- Shared API configuration\n\nForms and Validation\n- React Hook Form\n- Zod\n- Schema-based validation\n- Dynamic form configuration\n\nAuthentication and Access\n- AuthGate\n- Protected routes\n- Role-based access control\n- Cookie-based authentication\n\nAnalytics\n- Recharts\n- Dashboard visualizations\n- Data-driven tables and reporting\n\nEnvironment and Deployment\n- Development environment\n- Staging environment\n- Production environment\n- Vite environment configuration\n- PM2 process management\n\nKey Technical Areas\nReact | TypeScript | Vite | React Router | Radix UI | shadcn/ui | Tailwind CSS | React Query | Axios | React Hook Form | Zod | Recharts | RBAC | Authentication | Dynamic Forms | Reusable Components | Admin Dashboard | Multi-Environment Setup\n\nRole\nSoftware Developer - Frontend Development\n\nContributed to frontend architecture, feature development, reusable component development, API integration, form validation, authentication, role-based workflows, data visualization, administrative modules, and multi-environment application configuration.",
      techStack: ["React", "TypeScript", "Vite", "React Hook Form", "Zod", "Axios", "Razorpay"],
      projectImage: "",
      liveUrl: "",
      githubUrl: "",
      startDate: "",
      endDate: "",
      featured: true,
      displayOrder: 3,
    },
    {
      id: "proj-4",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      title: "Bank of India - Corporate Website",
      description:
        "Built responsive corporate website pages and reusable templates/components in Sitefinity CMS, ensuring cross-browser compatibility and brand consistency across sections.",
      slug: "bank-of-india-corporate-website",
      techStack: ["HTML", "CSS", "JavaScript", "Sitefinity CMS"],
      projectImage: "",
      liveUrl: "",
      githubUrl: "",
      startDate: "",
      endDate: "",
      featured: true,
      displayOrder: 4,
    },
    {
      id: "proj-5",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      title: "E-commerce App",
      description:
        "Full-featured online store with product filtering, cart, and checkout functionality.",
      slug: "ecommerce-app",
      techStack: ["React", "Redux", "Tailwind CSS"],
      projectImage: "",
      liveUrl: "https://ecommerce-theta-tan-34.vercel.app",
      githubUrl: "",
      startDate: "",
      endDate: "",
      featured: true,
      displayOrder: 5,
    },
    {
      id: "proj-6",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      title: "Crypto Tracker",
      description:
        "Real-time cryptocurrency prices and charts with authentication and wishlist features.",
      slug: "crypto-tracker",
      techStack: ["Next.js", "CoinGecko API", "Chart.js", "Clerk Auth"],
      projectImage: "",
      liveUrl: "https://crypto-git-main-rashvaths-projects.vercel.app",
      githubUrl: "",
      startDate: "",
      endDate: "",
      featured: true,
      displayOrder: 6,
    },
    {
      id: "proj-7",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      title: "WeatherNow",
      description:
        "Live weather updates with animated, location-aware responsive UI.",
      slug: "weathernow",
      techStack: ["React", "Weather API", "Tailwind CSS"],
      projectImage: "",
      liveUrl: "https://rashvath.github.io/WeatherNow",
      githubUrl: "",
      startDate: "",
      endDate: "",
      featured: true,
      displayOrder: 7,
    },
  ],
  skills: [
    {
      id: "skill-1",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      name: "JavaScript",
      proficiency: 90,
      category: "Languages",
      icon: "Code2",
      displayOrder: 1,
    },
    {
      id: "skill-2",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      name: "TypeScript",
      proficiency: 88,
      category: "Languages",
      icon: "FileCode",
      displayOrder: 2,
    },
    {
      id: "skill-3",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      name: "HTML5",
      proficiency: 90,
      category: "Languages",
      icon: "FileCode",
      displayOrder: 3,
    },
    {
      id: "skill-4",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      name: "CSS3",
      proficiency: 88,
      category: "Languages",
      icon: "FileCode",
      displayOrder: 4,
    },
    {
      id: "skill-5",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      name: "React.js",
      proficiency: 92,
      category: "Frontend",
      icon: "Code2",
      displayOrder: 5,
    },
    {
      id: "skill-6",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      name: "Next.js",
      proficiency: 89,
      category: "Frontend",
      icon: "Layout",
      displayOrder: 6,
    },
    {
      id: "skill-7",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      name: "Tailwind CSS",
      proficiency: 90,
      category: "Frontend",
      icon: "Layout",
      displayOrder: 7,
    },
    {
      id: "skill-8",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      name: "Material UI",
      proficiency: 84,
      category: "Frontend",
      icon: "Layout",
      displayOrder: 8,
    },
    {
      id: "skill-9",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      name: "Node.js",
      proficiency: 80,
      category: "Backend",
      icon: "Code2",
      displayOrder: 9,
    },
    {
      id: "skill-10",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      name: "Express.js",
      proficiency: 78,
      category: "Backend",
      icon: "Code2",
      displayOrder: 10,
    },
    {
      id: "skill-11",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      name: "PostgreSQL",
      proficiency: 78,
      category: "Databases",
      icon: "Database",
      displayOrder: 11,
    },
    {
      id: "skill-12",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      name: "Redux Toolkit",
      proficiency: 87,
      category: "State Management",
      icon: "Layout",
      displayOrder: 12,
    },
    {
      id: "skill-13",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      name: "React Query",
      proficiency: 85,
      category: "State Management",
      icon: "Layout",
      displayOrder: 13,
    },
    {
      id: "skill-14",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      name: "TanStack Query",
      proficiency: 85,
      category: "State Management",
      icon: "Layout",
      displayOrder: 14,
    },
    {
      id: "skill-15",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      name: "React Hook Form",
      proficiency: 87,
      category: "Validation & Forms",
      icon: "Layout",
      displayOrder: 15,
    },
    {
      id: "skill-16",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      name: "Formik",
      proficiency: 80,
      category: "Validation & Forms",
      icon: "Layout",
      displayOrder: 16,
    },
    {
      id: "skill-17",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      name: "Yup",
      proficiency: 78,
      category: "Validation & Forms",
      icon: "Layout",
      displayOrder: 17,
    },
    {
      id: "skill-18",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      name: "Zod",
      proficiency: 86,
      category: "Validation & Forms",
      icon: "Layout",
      displayOrder: 18,
    },
    {
      id: "skill-19",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      name: "Sitefinity CMS",
      proficiency: 76,
      category: "CMS",
      icon: "Wrench",
      displayOrder: 19,
    },
    {
      id: "skill-20",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      name: "Git",
      proficiency: 88,
      category: "Tools",
      icon: "Wrench",
      displayOrder: 20,
    },
    {
      id: "skill-21",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      name: "GitHub",
      proficiency: 88,
      category: "Tools",
      icon: "Wrench",
      displayOrder: 21,
    },
    {
      id: "skill-22",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      name: "VS Code",
      proficiency: 92,
      category: "Tools",
      icon: "Wrench",
      displayOrder: 22,
    },
    {
      id: "skill-23",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      name: "Vercel",
      proficiency: 82,
      category: "Tools",
      icon: "Wrench",
      displayOrder: 23,
    },
    {
      id: "skill-24",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      name: "Clerk",
      proficiency: 78,
      category: "Tools",
      icon: "Wrench",
      displayOrder: 24,
    },
    {
      id: "skill-25",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      name: "Axios",
      proficiency: 88,
      category: "Tools",
      icon: "Wrench",
      displayOrder: 25,
    },
    {
      id: "skill-26",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      name: "REST APIs",
      proficiency: 89,
      category: "Concepts",
      icon: "Code2",
      displayOrder: 26,
    },
    {
      id: "skill-27",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      name: "JWT Authentication",
      proficiency: 87,
      category: "Concepts",
      icon: "Code2",
      displayOrder: 27,
    },
    {
      id: "skill-29",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      name: "Middleware",
      proficiency: 86,
      category: "Concepts",
      icon: "Code2",
      displayOrder: 29,
    },
    {
      id: "skill-30",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      name: "RBAC",
      proficiency: 85,
      category: "Concepts",
      icon: "Code2",
      displayOrder: 30,
    },
    {
      id: "skill-31",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      name: "Secure Sessions",
      proficiency: 85,
      category: "Concepts",
      icon: "Code2",
      displayOrder: 31,
    },
    {
      id: "skill-33",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      name: "Responsive Design",
      proficiency: 90,
      category: "Concepts",
      icon: "Code2",
      displayOrder: 33,
    },
    {
      id: "skill-34",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      name: "Agile",
      proficiency: 85,
      category: "Concepts",
      icon: "Code2",
      displayOrder: 34,
    },
    {
      id: "skill-35",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      name: "Scrum",
      proficiency: 84,
      category: "Concepts",
      icon: "Code2",
      displayOrder: 35,
    },
  ],
  experience: [
    {
      id: "exp-1",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      companyName: "Ekfrazo Technologies Pvt. Ltd.",
      role: "Software Developer",
      duration: "Feb 2025 - Present",
      location: "Remote",
      description:
        "Joined as a Software Developer Intern and promoted to a full-time Software Developer based on consistent performance and project delivery.\n- Build scalable web applications using React, Next.js, and TypeScript.\n- Develop reusable UI components and design systems.\n- Integrate REST APIs and manage application state.\n- Implement secure authentication and authorization flows.\n- Optimize performance, accessibility, and responsive layouts.\n- Collaborate with backend developers, designers, and QA teams.\n- Maintain code quality through reviews, testing, and best practices.\n- Participate in Agile sprints, planning, and feature delivery.",
      technologiesUsed: [
        "React",
        "Next.js",
        "TypeScript",
        "Vite",
        "Redux Toolkit",
        "React Query",
        "TanStack Query",
        "React Hook Form",
        "Formik",
        "Yup",
        "Zod",
        "Axios",
        "JWT",
        "Node.js",
        "Express.js",
        "PostgreSQL",
        "Sitefinity CMS",
        "Jest",
        "Razorpay",
      ],
    },
  ],
  certifications: [
    {
      id: "cert-1",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      certificateName: "Introduction to Frontend Development",
      issuingOrganization: "SimpliLearn",
      issueDate: "May 2025",
      credentialUrl: "",
      certificateImage: "",
    },
    {
      id: "cert-2",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      certificateName: "React JS Bootcamp",
      issuingOrganization: "LetsUpgrade",
      issueDate: "Apr 2025",
      credentialUrl: "",
      certificateImage: "",
    },
    {
      id: "cert-3",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      certificateName: "React JS for Beginners",
      issuingOrganization: "SimpliLearn",
      issueDate: "May 2025",
      credentialUrl: "",
      certificateImage: "",
    },
  ],
  education: [
    {
      id: "edu-1",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      institutionName: "Dr. BB Hegde First Grade College, Kundapura",
      degree: "Bachelor of Computer Applications (BCA)",
      specialization: "Mangalore University",
      duration: "2021 - 2024",
      grade: "CGPA: 6.25",
    },
    {
      id: "edu-2",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      institutionName: "Seshadripuram PU College, Yelahanka, Bangalore",
      degree: "Pre-University (PU)",
      specialization: "",
      duration: "2019 - 2021",
      grade: "Percentage: 69%",
    },
  ],
  testimonials: [
    {
      id: "t-1",
      status: "published",
      updatedAt: now,
      publishedAt: now,
      name: "Engineering Lead",
      designation: "Technical Lead",
      company: "Ekfrazo Technologies",
      feedback:
        "Rashvath delivers reliable frontend solutions with strong ownership of authentication, architecture, and product quality.",
      profileImage: "",
    },
  ],
  contactInfo: {
    email: "rashvathshetty4@gmail.com",
    phone: "+91 9148050368",
    linkedIn: "https://linkedin.com/in/rashvath-shetty-507438286",
    github: "https://github.com/rashvath",
    twitterX: "",
    portfolioUrl: "https://www.rashvath-shetty.in/",
  },
  settings: {
    darkModeDefault: true,
    portfolioTheme: "modern-dark",
    primaryColor: "#3b82f6",
    secondaryColor: "#22d3ee",
    seoTitle: "Rashvath Shetty | Software Developer",
    seoDescription:
      "Portfolio of Rashvath Shetty, Software Developer specializing in React, Next.js, TypeScript, and secure web application architecture.",
    openGraphImage: "",
  },
  analytics: {
    portfolioVisits: 0,
    resumeDownloads: 0,
    contactFormSubmissions: 0,
    projectViews: {},
  },
  contactSubmissions: [],
  lastUpdated: now,
};
